//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhAn
    {
        public int IDBenhAn { get; set; }
        public string KetQua { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string BacSyKham { get; set; }
        public string DonThuoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDLichKham { get; set; }
    
        public virtual LichKham LichKham { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
