//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichKham
    {
        public LichKham()
        {
            this.BenhAns = new HashSet<BenhAn>();
        }
    
        public int IDLichKham { get; set; }
        public string ChuDe { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> BatDau { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string ZoomInfo { get; set; }
        public string KetQuaKham { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDQuanTri { get; set; }
    
        public virtual ICollection<BenhAn> BenhAns { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual QuanTri QuanTri { get; set; }
    }
}
