//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTri
    {
        public QuanTri()
        {
            this.HoiDaps = new HashSet<HoiDap>();
            this.LichKhams = new HashSet<LichKham>();
        }
    
        public int IDQuanTri { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string ThongTinBacSi { get; set; }
        public string TrinhDo { get; set; }
        public Nullable<int> IDKhoa { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> VaiTro { get; set; }
        public string AnhBia { get; set; }
        public string ThongtinZoom { get; set; }
    
        public virtual ICollection<HoiDap> HoiDaps { get; set; }
        public virtual Khoa Khoa { get; set; }
        public virtual ICollection<LichKham> LichKhams { get; set; }
    }
}
