//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiDap
    {
        public int IDHoidap { get; set; }
        public string CauHoi { get; set; }
        public string TraLoi { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDQuanTri { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual QuanTri QuanTri { get; set; }
    }
}
