//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAppYteEntities : DbContext
    {
        public WebAppYteEntities()
            : base("name=WebAppYteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BenhAn> BenhAns { get; set; }
        public DbSet<GioiTinh> GioiTinhs { get; set; }
        public DbSet<HoiDap> HoiDaps { get; set; }
        public DbSet<Khoa> Khoas { get; set; }
        public DbSet<LichKham> LichKhams { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<QuanTri> QuanTris { get; set; }
        public DbSet<Solieucovid> Solieucovids { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TinhThanh> TinhThanhs { get; set; }
        public DbSet<Tintuc> Tintucs { get; set; }
        public DbSet<TrungTamGanNhat> TrungTamGanNhats { get; set; }
    }
}
