//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.BenhAns = new HashSet<BenhAn>();
            this.HoiDaps = new HashSet<HoiDap>();
            this.LichKhams = new HashSet<LichKham>();
        }
    
        public int IDNguoiDung { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> IDGioiTinh { get; set; }
        public string DiaChiCuThe { get; set; }
        public Nullable<int> SoCMND { get; set; }
        public Nullable<int> IDTinh { get; set; }
        public string NhomMau { get; set; }
        public string ThongTinKhac { get; set; }
    
        public virtual ICollection<BenhAn> BenhAns { get; set; }
        public virtual GioiTinh GioiTinh { get; set; }
        public virtual ICollection<HoiDap> HoiDaps { get; set; }
        public virtual ICollection<LichKham> LichKhams { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
