//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.BenhAns = new HashSet<BenhAn>();
            this.HoiDaps = new HashSet<HoiDap>();
            this.LichKhams = new HashSet<LichKham>();
        }

        public int IDNguoiDung { get; set; }

        [Required(ErrorMessage = "Cần nhập họ tên")]
        public string HoTen { get; set; }

        [Required(ErrorMessage = "Cần nhập Email")]
        [EmailAddress(ErrorMessage = "Email không phù hợp")]
        public string Email { get; set; }   // validation

        [Required(ErrorMessage = "Cần nhập số điện thoại")]
        [Phone(ErrorMessage = "Số điện thoại không phù hợp")]
        [RegularExpression(@"^\d{9,10}$", ErrorMessage = "Số điện thoại không phù hợp")]
        public string DienThoai { get; set; }   //validation

        [Required(ErrorMessage = "Cần nhập tài khoản")]
        [RegularExpression(@"^[a-zA-Z0-9]+$", ErrorMessage = "Tài khoản chỉ được chứa các ký tự A-Z,a-z,0-9")]
        public string TaiKhoan { get; set; }    //validation

        [Required(ErrorMessage = "Cần nhập mật khẩu")]
        public string MatKhau { get; set; }
        public Nullable<int> IDGioiTinh { get; set; }
        public string DiaChiCuThe { get; set; }
        public Nullable<int> SoCMND { get; set; }

        public Nullable<int> IDTinh { get; set; }   //validation

        [Required(ErrorMessage = "Cần nhập nhóm máu")]
        [RegularExpression(@"^(A|B|AB|O)[+-]$", ErrorMessage = "Nhóm máu không phù hợp")]
        public string NhomMau { get; set; }     //validation
        public string ThongTinKhac { get; set; }

        public virtual ICollection<BenhAn> BenhAns { get; set; }
        public virtual GioiTinh GioiTinh { get; set; }
        public virtual ICollection<HoiDap> HoiDaps { get; set; }
        public virtual ICollection<LichKham> LichKhams { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
