//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhThanh
    {
        public TinhThanh()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
            this.TrungTamGanNhats = new HashSet<TrungTamGanNhat>();
        }
    
        public int IDTinh { get; set; }
        public string TenTinh { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        public virtual ICollection<TrungTamGanNhat> TrungTamGanNhats { get; set; }
    }
}
