//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthhub_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrungTamGanNhat
    {
        public int IDTrungTam { get; set; }
        public string TenTrungTam { get; set; }
        public string Mota { get; set; }
        public Nullable<int> IDTinh { get; set; }
    
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
